all: a_star.cpp
	g++ -std=c++0x -O2 main.cpp a_star.cpp grid.cpp distance_estimators.cpp -o a_star

a_star.cpp: a_star.h

a_star.h: grid.cpp

grid.cpp: grid.h

grid.h:

distance_estimators.h:

distance_estimators.cpp:

